on: push
name: New workflow
jobs:
  dockerRegistry:
    name: Docker Registry
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Docker Registry
      uses: actions/docker/login@86ab5e854a74b50b7ed798a94d9b8ce175d8ba19
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    - name: Build Frontend
      uses: actions/docker/cli@86ab5e854a74b50b7ed798a94d9b8ce175d8ba19
      with:
        args: build -t tdr-diff-client ./services/client
    - name: Build Backend
      uses: actions/docker/cli@86ab5e854a74b50b7ed798a94d9b8ce175d8ba19
      with:
        args: build -t tdr-diff-backend ./services/server
    - name: Docker Tag Frontend
      uses: actions/docker/tag@86ab5e854a74b50b7ed798a94d9b8ce175d8ba19
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      with:
        args: tdr-diff-client ${DOCKER_USERNAME}/tdr-diff-client
    - name: Docker Tag Backend
      uses: actions/docker/tag@86ab5e854a74b50b7ed798a94d9b8ce175d8ba19
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      with:
        args: tdr-diff-backend ${DOCKER_USERNAME}/tdr-diff-backend
    - name: Docker Push Frontend
      uses: actions/docker/cli@86ab5e854a74b50b7ed798a94d9b8ce175d8ba19
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      with:
        args: push ${DOCKER_USERNAME}/tdr-diff-client:${IMAGE_SHA}
    - name: Docker Push Backend
      uses: actions/docker/cli@86ab5e854a74b50b7ed798a94d9b8ce175d8ba19
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      with:
        args: push ${DOCKER_USERNAME}/tdr-diff-backend:${IMAGE_SHA}
